# Generated by Django 5.0.6 on 2026-10-04 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_answer_options_alter_attempt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='pass_score',
            field=models.PositiveIntegerField(default=70, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Проходной балл (%)'),
        ),
    ]
