# Generated by Django 5.0.6 on 2026-10-04 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('quizzes', '0004_alter_attempt_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(check=models.Q(('score__lte', 100)), name='attempt_score_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(check=models.Q(('pass_score__lte', 100)), name='quiz_pass_score_lte_100'),
        ),
    ]
